config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
   }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end

  resources :image_posts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get :liked_users
    end
  end

  resources :recruitments, except: [:show] do
    member do
      get :liked_users
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :image_post_likes, only: [:create, :destroy]
  resources :recruitment_likes, only: [:create, :destroy]
  resources :talk_rooms, only: [:show] do
    resources :messages, only: [:create, :destroy]
  end
  resources :notifications, only: :index
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :talk_room
  has_many :notifications, dependent: :destroy
  validates :user_id, presence: true
  validates :talk_room_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  scope :recent, -> { order(created_at: :desc) }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :correct_user, only: :destroy

  def create
    @talk_room = TalkRoom.find(params[:talk_room_id])
    @message = current_user.messages.build(message_params)
    @message.talk_room_id = @talk_room.id
    @message.save
    @talk_room.recruitment.create_comment_notification(current_user, @message)
    @messages = @talk_room.messages.includes(:user).recent
  end

  def destroy
    @message.destroy
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def correct_user
    @message = current_user.messages.find_by(id: params[:id])
    redirect_to root_url if @message.nil?
  end
end

app/views/messages/_message.html.slim
- unless current_user?(message.user)
  .incoming_msg.mb-4 id="message-#{message.id}"
    .incoming_msg_img
      = gravatar_for(message.user, size: 45)
      .text-muted.text-center.user_name= message.user.name
    .received_msg
      .received_withd_msg
        = simple_format(h(message.content), {}, sanitize: false)
        span.time_date
          = "#{time_ago_in_words(message.created_at).upcase} 前"
- else
  .outgoing_msg id="message-#{message.id}"
    .sent_msg
      = simple_format(h(message.content), {}, sanitize: false)
      span.time_date
        = "#{time_ago_in_words(message.created_at).upcase} 前"
        = link_to "削除", talk_room_message_path(@talk_room, message), method: :delete, remote: true, class: "ml-4"

app/views/messages/create.js.erb
<% if @message.errors.any? %>
  $("#message_form").html("<%= escape_javascript(render('shared/message_form')) %>")
<% else %>
  $("#message_content").val('');
  $(".error-list").css('display', 'none');
  $(".field_with_errors").removeClass("field_with_errors")
  $("#messages").html("<%= escape_javascript(render(partial: 'message', collection: @messages)) %>");
  $("#talk_users").html("<%= escape_javascript(render('talk_rooms/talk_users', users: @talk_room.users)) %>");
<% end %>

app/views/messages/destroy.js.erb
$("#message-<%= @message.id %>").css("display", "none");