config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
   }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end

  resources :image_posts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get :liked_users
    end
  end

  resources :recruitments, except: [:show] do
    member do
      get :liked_users
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :image_post_likes, only: [:create, :destroy]
  resources :recruitment_likes, only: [:create, :destroy]
  resources :talk_rooms, only: [:show] do
    resources :messages, only: [:create, :destroy]
  end
  resources :notifications, only: :index
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :image_post, optional: true
  belongs_to :comment, optional: true
  belongs_to :recruitment, optional: true
  belongs_to :message, optional: true
  belongs_to :visitor, class_name: "User", foreign_key: "visitor_id", optional: true
  belongs_to :visited, class_name: "User", foreign_key: "visited_id", optional: true
  validates :visitor_id, presence: true
  validates :visited_id, presence: true
  validates :action, presence: true
  scope :recent, -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.where.not(visitor: current_user).
      includes(:visitor, :visited, :image_post, :comment, :recruitment, :message).
      page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_action.html.slim
- case notification.action
- when 'follow'
  = "あなたをフォローしました"
- when 'image_post_like'
  = link_to 'あなたの投稿', notification.image_post, class: "text-muted font-md", style: "font-weight: bold;"
  = "にいいねしました"
- when 'recruitment_like'
  = link_to 'あなたの募集', notification.recruitment.talk_room, class: "text-muted font-md", style: "font-weight: bold;"
  = "にいいねしました"
- when 'image_post_comment'
  - if notification.image_post.user_id == visited.id
    = link_to "あなたの投稿", notification.image_post, class: "text-muted font-md", style: "font-weight: bold;"
  - else
    span
      = link_to image_post_path(notification.image_post) do
        = gravatar_for(visitor, size: 35)
        strong
          = notification.image_post.user.name + 'さんの投稿'
  = "にコメントしました"
  p.text-muted.mb-0
    = notification.comment&.content
- when 'recruitment_comment'
  - if notification.recruitment.user_id == visited.id
    = link_to "あなたの募集ルーム", notification.recruitment.talk_room, class: "text-muted font-md", style: "font-weight: bold;"
  - else
    span
      = link_to talk_room_path(notification.recruitment.talk_room) do
        = gravatar_for(visitor, size: 35)
        strong
          = notification.recruitment.user.name + 'さんの募集ルーム'
  = "にコメントしました"
  p.text-muted.mb-0
    = notification.message&.content

app/views/notifications/_notification.html.slim
- visitor = notification.visitor
- visited = notification.visited
.col-md-8.mx-auto.mt-4.notification
  .row.align-items-center
    .col-md-1
      = gravatar_for(visitor, size: 40)
    .col-md-9
      .form-inline
        span
          = link_to user_path(visitor) do
            strong.text-muted.font-md= visitor.name
          | さんが
          = render partial: 'notifications/action', locals: { visitor: visitor, visited: visited, notification: notification}
    .col-md-2.d-flex.align-self-end
      .small.text-muted
        = "#{time_ago_in_words(notification.created_at).upcase} 前"
  hr

app/views/notifications/index.html.slim
.container
  - if @notifications.exists?
    .row#notifications
      = render @notifications
    .page-load-status.text-center.text-muted
      .infinite-scroll-request
        | ...
        = paginate @notifications
      p.infinite-scroll-last
        | end of contents
  - else
    p
      | 通知はありません