config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
   }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end

  resources :image_posts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get :liked_users
    end
  end

  resources :recruitments, except: [:show] do
    member do
      get :liked_users
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :image_post_likes, only: [:create, :destroy]
  resources :recruitment_likes, only: [:create, :destroy]
  resources :talk_rooms, only: [:show] do
    resources :messages, only: [:create, :destroy]
  end
  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(facebook twitter google_oauth2)

  has_many :image_posts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :image_post_likes, dependent: :destroy
  has_many :liked_image_posts, through: :image_post_likes, source: :image_post
  has_many :comments, dependent: :destroy
  has_many :recruitments, dependent: :destroy
  has_many :recruitment_likes, dependent: :destroy
  has_many :liked_recruitments, through: :recruitment_likes, source: :recruitment
  has_many :messages, dependent: :destroy
  has_many :active_notifications, class_name: "Notification",
                                  foreign_key: "visitor_id",
                                  dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
                                   foreign_key: "visited_id",
                                   dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, length: { maximum: 255 }
  validates :introduction, length: { maximum: 200 }
  validate :picture_size
  PICTURE_SIZE = [110, 110].freeze
  mount_uploader :picture, PictureUploader

  def self.from_omniauth(auth)
    # Omniauth認証するたびに認証先ユーザー情報（名前など）が取得される。
    user = find_or_initialize_by(provider: auth.provider, uid: auth.uid)
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.name = auth.info.name
    user
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'UserGuest') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # deviseのupdate_without_passwordを参考に
  def update_without_current_password(params)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params)
    clean_up_passwords
    result
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def image_like(image_post)
    liked_image_posts << image_post
  end

  def image_unlike(image_post)
    image_post_likes.find_by(image_post_id: image_post.id).destroy
  end

  def image_like?(image_post)
    liked_image_posts.include?(image_post)
  end

  def recruitment_like(recruitment)
    liked_recruitments << recruitment
  end

  def recruitment_unlike(recruitment)
    recruitment_likes.find_by(recruitment_id: recruitment.id).destroy
  end

  def recruitment_like?(recruitment)
    liked_recruitments.include?(recruitment)
  end

  def create_follow_notification(current_user)
    temp = passive_notifications.where(
      "visitor_id = ? and action = ?", current_user.id, 'follow'
    )
    if temp.blank?
      notification = current_user.active_notifications.build(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  private

  def picture_size
    if picture.size > 2.megabytes
      errors.add(:picture, "画像は2MB未満にしてください")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback
  end

  def twitter
    callback
  end

  def google_oauth2
    callback
  end

  def failure
    redirect_to root_path
  end

  private

  def callback
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.save
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{user.provider}") if is_navigational_format?
    else
      set_flash_message(
        :alert, :failure,
        kind: "#{user.provider}", reason: "「#{user.email}」は既に別のアカウントで使用されています"
      )
      session["devise.user_attirbutes"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  # deviseのfind_messageをオーバーライド, google_oauth2認証時はフラッシュメッセージを変更している
  def find_message(kind, options = {})
    options[:scope] ||= translation_scope
    options[:default] = Array(options[:default]).unshift(kind.to_sym)
    options[:resource_name] = resource_name
    options[:kind] = "Google" if options[:kind] == "google_oauth2"
    options = devise_i18n_options(options)
    I18n.t("#{options[:resource_name]}.#{kind}", **options)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  private

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @image_posts = @user.image_posts.recent.page(params[:page]).per(12)
    @image_post = current_user.image_posts.build
  end

  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(20)
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(20)
    render 'show_follow'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # gravatarの使用は廃止、自由にプロフ画を変更できるように修正
  def gravatar_for(user, size: 110)
    if user.picture?
      image_tag(
        user.picture.url, alt: user.name,
                          class: "rounded-circle", width: "#{size}px", height: "auto"
      )
    else
      image_tag(
        "dafault.png", alt: user.name,
                       class: "rounded-circle", width: "#{size}px", height: "auto"
      )
    end
  end
end

app/views/users/_current_user.html.slim
.row.justify-content-center
  .col-md-7.col-sm-6
    .text-center.py-5
      = gravatar_for(user)
      .col-md-8.col-lg-6.col-xl-5.p-0.mx-auto
        h4.font-weight-bold.my-4
          = link_to user.name, edit_user_registration_path, class: "text-dark"
        .text-muted.mb-4
          = user.introduction
  .col-md-5.col-sm-6.align-self-center
    = render 'shared/imagepost_form', image_post: @image_post

app/views/users/_follow.html.slim
= form_for(current_user.active_relationships.build, remote: true) do |f|
  .= hidden_field_tag :followed_id, user.id
  = f.submit "フォローする", class: "btn btn-info btn-sm"

app/views/users/_follow_form.html.slim
div#follow_form
  - if current_user.following?(user)
    = render 'unfollow', user: user
  - else
    = render 'follow', user: user

app/views/users/_following_follower_count.html.slim
= link_to following_user_path(user), class: "d-inline-block text-dark" do
  strong.mr-1
    = user.following.count
  span.text-muted
    | フォロー
= link_to followers_user_path(user), class: "d-inline-block text-dark ml-3" do
  strong.mr-1#followers
    = user.followers.count
  span.text-muted
    | フォロワー

app/views/users/_other_user.html.slim
.text-center.py-5
  = gravatar_for(user)
  .col-md-8.col-lg-6.col-xl-5.p-0.mx-auto
    h4.font-weight-bold.my-4
      = user.name
    .text-muted.mb-4
      = user.introduction

app/views/users/_profile.html.slim
- if current_user?(user)
  = render 'users/current_user', user: user
- else
  = render 'users/other_user', user: user

app/views/users/_unfollow.html.slim
= form_for(current_user.active_relationships.find_by(followed_id: user.id),
            html: { method: :delete }, remote: true) do |f|
  = f.submit "フォロー中", class: "btn btn-secondary btn-sm"

app/views/users/_user.html.slim
.followers-box.full-width.user
  .followers-list
    .followers-body
      = gravatar_for(user, size: 40)
      .name-box
        h4
          = link_to user.name, user_path(user), class: "text-muted"
        span
          = user.introduction
        .followers-base.mt-2
          p.mb-1
            = user.following.count
            | フォロー
          p.mb-0
            = user.followers.count
            | フォロワー

app/views/users/show.html.slim
= provide(:title, "#{@user.name}")
.container
  .d-flex.justify-content-between.align-items-center.py-4
    div
      = render 'users/following_follower_count', user: @user
    - unless current_user?(@user)
      = render 'users/follow_form', user: @user
hr.m-0
.container
  = render 'users/profile', user: @user
hr.m-0
  - if @user.image_posts.any?
    .container.mt-4
      .row.text-center#image_posts
        = render @image_posts
      .page-load-status.text-center.text-muted
        .infinite-scroll-request
          | ...
          = paginate @image_posts
        p.infinite-scroll-last
          | end of contents

app/views/users/show_follow.html.slim
= provide(:title, @title)
.container
  h3.text-muted.mt-2= @title
  .row.mt-3
    .col-md-5
      .followers-box.full-width
        .followers-list
          .followers-body
            = gravatar_for(@user, size: 60)
            .name-box
              h4.mt-3.mb-2
                = link_to @user.name, user_path(@user), class: "text-muted"
              .followers-base
                p.mb-1
                  = @user.following.count
                  | フォロー
                p.mb-0
                  = @user.followers.count
                  | フォロワー
    - if @users.any?
      = render 'shared/users', users: @users