config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
   }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: :show do
    member do
      get :following, :followers
    end
  end

  resources :image_posts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get :liked_users
    end
  end

  resources :recruitments, except: [:show] do
    member do
      get :liked_users
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :image_post_likes, only: [:create, :destroy]
  resources :recruitment_likes, only: [:create, :destroy]
  resources :talk_rooms, only: [:show] do
    resources :messages, only: [:create, :destroy]
  end
  resources :notifications, only: :index
end

app/models/image_post.rb
class ImagePost < ApplicationRecord
  include Notice

  belongs_to :user
  has_many :image_post_likes, dependent: :destroy
  has_many :liked_users, through: :image_post_likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user
  has_many :notifications, dependent: :destroy
  validates :picture, presence: { message: "を選択してください" }
  validates :user_id, presence: true
  validates :content, length: { maximum: 140 }
  validate :picture_size
  scope :recent, -> { order(created_at: :desc) }
  PICTURE_SIZE = [900, 600].freeze
  mount_uploader :picture, PictureUploader

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "画像は5MB未満にしてください")
    end
  end
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
  before_action :correct_user, only: :destroy

  def show
    @image_post = ImagePost.find(params[:id])
    @comments = @image_post.comments.includes(:user).recent
    @user = @image_post.user
    @comment = current_user.comments.build
  end

  def create
    @image_post = current_user.image_posts.build(image_post_params)
    if @image_post.save
      redirect_to current_user, notice: '画像を投稿しました。'
    else
      @image_posts = current_user.image_posts.recent.page(params[:page])
      @user = current_user
      render 'users/show'
    end
  end

  def destroy
    @image_post.destroy
    flash[:notice] = '画像を削除しました'
    redirect_to @image_post.user
  end

  def liked_users
    @image_post = ImagePost.find(params[:id])
    @user = @image_post.user
    @users = @image_post.liked_users.page(params[:page]).per(20)
  end

  private

  def image_post_params
    params.require(:image_post).permit(:picture, :content)
  end

  def correct_user
    @image_post = current_user.image_posts.find_by(id: params[:id])
    redirect_to root_url if @image_post.nil?
  end
end

app/views/image_posts/_image_like.html.slim
= form_for(current_user.image_post_likes.build, html: { style: "display: inline-block;" }, remote: true) do |f|
  .= hidden_field_tag :image_post_id, image_post.id
  = f.button type: "submit", class: "like-button" do
    i.far.fa-heart

app/views/image_posts/_image_post.html.slim
.col-lg-4.col-md-4.col-12.image_post
  = link_to image_tag(image_post.picture.url, class: "img-fluid post-img-list"), image_post_path(image_post), class: "d-block mb-4"

app/views/image_posts/_image_unlike.html.slim
= form_for(current_user.image_post_likes.find_by(image_post_id: image_post.id),
            html: { method: :delete, style: "display: inline-block;" }, remote: true) do |f|
  = f.button type: "submit", class: "unlike-button" do
    i.fas.fa-heart

app/views/image_posts/_likes_count.html.slim
= link_to "#{image_post.liked_users.count} いいね！", liked_users_image_post_path(image_post)

app/views/image_posts/_status.html.slim
li.list-inline-item
  = gravatar_for(user, size: 40)
  = link_to user.name, user, class: "ml-1"
li.list-inline-item
  span#image_like_form
    - if current_user.image_like?(image_post)
      = render 'image_posts/image_unlike', image_post: image_post
    - else
      = render 'image_posts/image_like', image_post: image_post
  span#likes-count
    = render 'image_posts/likes_count', image_post: image_post
- if current_user?(image_post.user)
  li.list-inline-item
    = link_to "削除", image_post_path(image_post), data: { confirm: "削除しますか？" }, method: :delete

app/views/image_posts/liked_users.html.slim
= provide(:title, 'People who liked the post')
.container
  h3.text-muted.mt-2= @title
  .row.mt-3
    .col-md-5
      .followers-box.full-width
        .followers-list
          .followers-body
            = image_tag(@image_post.picture.url, class: "img-fluid mb-3 rounded")
            .post-content
              = simple_format(h(@image_post.content), {}, sanitize: false, wrapper_tag: "div")
              ul.post-meta.list-inline
                = render 'image_posts/status', user: @user, image_post: @image_post
    - if @users.any?
      = render 'shared/users', users: @users

app/views/image_posts/show.html.slim
= provide(:title, "Posted by #{@image_post.user.name}")
.container
  .row.mt-4.justify-content-center
    .col-md-7.mb-3
      = image_tag(@image_post.picture.url, class: "img-fluid mb-3 rounded")
      .post-content
        = simple_format(h(@image_post.content), {}, sanitize: false, wrapper_tag: "div")
        ul.post-meta.list-inline
          = render 'status', user: @user, image_post: @image_post
        hr.mb-3
          #comment_form
            = render 'shared/comment_form'
    .col-md-5.comment-area.overflow-auto
      div
        h4.sidebar-title
          | コメント一覧
        ul.list-unstyled#comments
          - if @image_post.comments.any?
            = render @comments